export {default as Profile} from '@/assets/svgs/profile-circle.svg'
export {default as Search} from '@/assets/svgs/search-normal.svg'
export {default as Logo} from '@/assets/svgs/logo.svg'
export {default as MintCoin} from '@/assets/svgs/mingcute_coin-3-fill.svg'
export {default as Download} from '@/assets/svgs/download.svg'
export {default as Caret} from '@/assets/svgs/caret.svg'
